name: "pre0.3.1 testing"

on:
  push:
    branches:
      - "0.3.1"

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  pre-release:
    name: "pre0.3.1 testing"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: liberica
        java-version: 17.0.14+10
        java-package: jdk+fx

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper

    - name: Execute Windows Gradle build
      run: ./gradlew -Dplatform=windows shadowJar
    - name: Execute Linux Gradle build
      run: ./gradlew -Dplatform=linux shadowJar
    - name: Execute Macos(x86) Gradle build
      run: ./gradlew -Dplatform=macos shadowJar
    - name: Execute Macos(arm) Gradle build
      run: ./gradlew -Dplatform=macos -Darch=aarch64 shadowJar

    - name: Make Github release with build artifacts
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "pre0.3.1"
        prerelease: true
        title: "pre0.3.1 Testing Build"
        files: |
          dist/*
